services:
  init:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FSSPEC_S3_ENDPOINT_URL=https://obs.eu-de.otc.t-systems.com
      - FSSPEC_S3_KEY=
      - FSSPEC_S3_SECRET=