logging:
  level: DEBUG
  logfile: /dev/stdout
metadata:
  contact:
    address: Mailing Address
    city: City
    country: Canada
    email: you@example.org
    fax: +xx-xxx-xxx-xxxx
    hours: Hours of Service
    instructions: During hours of service. Off on weekends.
    name: Kralidis, Tom
    phone: +xx-xxx-xxx-xxxx
    position: Lead Dev
    postalcode: Zip or Postal Code
    role: pointOfContact
    stateorprovince: Administrative Area
    url: Contact URL
  identification:
    description: pygeoapi provides an API to geospatial data
    keywords:
    - geospatial
    - data
    - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    title: pygeoapi icisk
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: pygeoapi Development Team
    url: https://pygeoapi.io
resources:
  ingestKNMI:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorKNMIProcessProcessor
    type: process
  knmi_evapo_obs:
    description: pot precip deficit obs
    extents:
      spatial:
        bbox:
        - 3.292034674366435
        - 50.71517388522664
        - 7.289092584241217
        - 53.5792215153204
        crs: http://www.opengis.net/def/crs/EPSG/0/4326
    keywords:
    - country
    providers:
    - data:
        dbname: postgres
        host: postgis
        password: password
        port: 5432
        search_path:
        - public
        user: postgres
      geom_field: geometry
      id_field: index
      name: PostgreSQL
      table: knmi_obs
      type: feature
    title: knmi_evapo_obs
    type: collection
  knmi_evapo_obs_2024:
    description: knmi_evapo_obs of 2024
    extents:
      spatial:
        bbox:
        - 500.0
        - 290500.0
        - 299500.0
        - 639500.0
        crs: http://www.opengis.net/def/crs/EPSG/0/28992
    keywords:
    - country
    providers:
    - data: s3://52n-i-cisk/data-ingestor/knmi_2024.zarr
      format:
        mimetype: application/zip
        name: zarr
      name: xarray-edr
      options:
        s3:
          alternate_root: 52n-i-cisk/data-ingestor/knmi_2024.zarr
          anon: false
          endpoint_url: https://obs.eu-de.otc.t-systems.com
          requester_pays: false
      time_field: time
      type: edr
      x_field: x
      y_field: y
    title: knmi_evapo_obs_2024
    type: collection
server:
  bind:
    host: 0.0.0.0
    port: 80
  cors: true
  encoding: utf-8
  gzip: false
  language: en-US
  limit: 10000
  manager:
    connection: /tmp/pygeoapi-process-manager.db
    name: TinyDB
    output_dir: /tmp/
  map:
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  mimetype: application/json; charset=UTF-8
  ogc_schemas_location: /schemas.opengis.net
  pretty_print: true
  url: http://localhost:5000
