server:
  bind:
    host: 0.0.0.0
    port: 80
  url: http://localhost:5000/
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  language: en-US
  cors: true
  pretty_print: true
  limit: 10
  map:
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  ogc_schemas_location: /schemas.opengis.net
  manager:
    name: TinyDB
    connection: /tmp/pygeoapi-process-manager.db
    output_dir: /tmp/
logging:
  level: DEBUG
  logfile: /dev/stdout
metadata:
  identification:
    title: pygeoapi icisk
    description: pygeoapi provides an API to geospatial data
    keywords:
    - geospatial
    - data
    - api
    - living-labs
    - i-cisk
    - 52north
    - gecko
    keywords_type: theme
    terms_of_service: 'FIXME: https://icisk.eu/about-icisk/'
    url: https://i-cisk.dev.52north.org/data/
  license:
    name: 'FIXME: TBD, maybe CC-BY 4.0 license'
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: "52\xB0North I-Cisk Team"
    url: https://52north.org/solutions/i-cisk/
  contact:
    name: "J\xFCrrens, Eike Hinderk"
    position: Operator
    address: Martin-Luther-King-Weg 24
    city: "M\xFCnster"
    stateorprovince: NRW
    postalcode: 48155
    country: Germany
    phone: +49-251-396371-0
    email: e.h.juerrens+i-cisk-cloud-ops@52north.org
    url: https://52north.org/about-us/contact-us/
    hours: Mo-Fr 09:00-16:00 CE(S)T
    instructions: During hours of service. Off on weekends.
    role: pointOfContact
resources:
  ingestor-cds-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSProcessProcessor
    type: process
  ingestor-creafforecast-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCREAFFORECASTProcessProcessor
    type: process
  ingestor-creafhistoric-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCREAFHISTORICProcessProcessor
    type: process
  ingestor-smhi-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorSMHIProcessProcessor
    type: process
  ingestor-smhi-vector-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorSMHIVectorProcessProcessor
    type: process
  ingestor-cds-spi-historic-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSSPIHistoricProcessProcessor
    type: process
  ingestor-cds-spi-forecast-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSSPIForecastProcessProcessor
    type: process
  georgia_spi_forecast:
    type: collection
    title: georgia_spi_forecast
    description: SPI for georgia
    keywords:
    - country
    extents:
      spatial:
        bbox:
        - 45.196
        - 41.12
        - 46.697
        - 42.021
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2025-02-01 00:00:00
        end: 2025-06-01 00:00:00
    providers:
    - type: edr
      name: xarray-edr
      data: s3://saferplaces.co/test/icisk/spi/spi_data/forecast/spi_forecast_georgia_test_11.zarr
      x_field: lon
      y_field: lat
      time_field: time
      format:
        name: zarr
        mimetype: application/zip
      options:
        s3:
          anon: false
          alternate_root: saferplaces.co/test/icisk/spi/spi_data/forecast/spi_forecast_georgia_test_11.zarr
          endpoint_url: https://s3.us-east-1.amazonaws.com
          requester_pays: false
  georgia_spi_historic:
    type: collection
    title: georgia_spi_historic
    description: SPI for georgia
    keywords:
    - country
    extents:
      spatial:
        bbox:
        - 45.196
        - 41.12
        - 46.697
        - 42.021
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2024-09-01 00:00:00
        end: 2025-01-01 00:00:00
    providers:
    - type: edr
      name: xarray-edr
      data: s3://saferplaces.co/test/icisk/spi/spi_data/historic/spi_historic_georgia_test_00.zarr
      x_field: lon
      y_field: lat
      time_field: time
      format:
        name: zarr
        mimetype: application/zip
      options:
        s3:
          anon: false
          alternate_root: saferplaces.co/test/icisk/spi/spi_data/historic/spi_historic_georgia_test_00.zarr
          endpoint_url: https://s3.us-east-1.amazonaws.com
          requester_pays: false
