logging:
  level: DEBUG
  logfile: /dev/stdout
metadata:
  contact:
    address: Mailing Address
    city: City
    country: Canada
    email: you@example.org
    fax: +xx-xxx-xxx-xxxx
    hours: Hours of Service
    instructions: During hours of service. Off on weekends.
    name: Kralidis, Tom
    phone: +xx-xxx-xxx-xxxx
    position: Lead Dev
    postalcode: Zip or Postal Code
    role: pointOfContact
    stateorprovince: Administrative Area
    url: Contact URL
  identification:
    description: pygeoapi provides an API to geospatial data
    keywords:
    - geospatial
    - data
    - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    title: pygeoapi icisk
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: pygeoapi Development Team
    url: https://pygeoapi.io
resources:
  creaf_forecast:
    description: creaf_forecast of precipitation
    extents:
      spatial:
        bbox:
        - 107963.51010420798
        - 4012553.4808084117
        - 628263.690765058
        - 4347991.887574628
        crs: http://www.opengis.net/def/crs/EPSG/0/25830
    keywords:
    - country
    providers:
    - data: s3://52n-i-cisk/data-ingestor/creaf_forecast_auto_test.zarr
      format:
        mimetype: application/zip
        name: zarr
      name: xarray-edr
      options:
        s3:
          alternate_root: 52n-i-cisk/data-ingestor/creaf_forecast_auto_test.zarr
          anon: false
          endpoint_url: https://obs.eu-de.otc.t-systems.com
          requester_pays: false
      time_field: time
      type: edr
      x_field: longitude
      y_field: latitude
    title: creaf_forecast
    type: collection
  ingestor-cds-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSProcessProcessor
    type: process
  ingestor-creafforecast-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCREAFFORECASTProcessProcessor
    type: process
  ingestor-smhi-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorSMHIProcessProcessor
    type: process
  ingestor-smhi-vector-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorSMHIVectorProcessProcessor
    type: process
server:
  bind:
    host: 0.0.0.0
    port: 80
  cors: true
  encoding: utf-8
  gzip: false
  language: en-US
  limit: 10
  manager:
    connection: /tmp/pygeoapi-process-manager.db
    name: TinyDB
    output_dir: /tmp/
  map:
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  mimetype: application/json; charset=UTF-8
  ogc_schemas_location: /schemas.opengis.net
  pretty_print: true
  url: http://localhost:5000
