# =================================================================
#
# Authors: Just van den Broecke <justb4@gmail.com>
#          Tom Kralidis <tomkralidis@gmail.com>
#          Francesco Bartoli <xbartolone@gmail.com>
#
# Copyright (c) 2019 Just van den Broecke
# Copyright (c) 2020 Tom Kralidis
# Copyright (c) 2020 Francesco Bartoli
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================


# Default config for base Docker Image, override via DockerVolume
# mapping with your own config.
server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net
    manager:  # optional OGC API - Processes asynchronous job management
      name: TinyDB  # plugin name (see pygeoapi.plugin for supported process_manager's)
      connection: /tmp/pygeoapi-process-manager.db  # connection info to store jobs (e.g. filepath)
      output_dir: /tmp/  # temporary file area for storing job results (files)

logging:

  level: DEBUG
  logfile: /dev/stdout
metadata:
    identification:
        title: pygeoapi icisk
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/geopython/pygeoapi
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: pygeoapi Development Team
        url: https://pygeoapi.io
    contact:
        name: Kralidis, Tom
        position: Lead Dev
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Canada
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:

    georgia_smhi_data:
        type: collection
        title: georgia_smhi_data
        description: SMHI Discharge data of Georgia
        keywords:
            - Georgia
            - country
        links:
            - type: text/html
              rel: canonical
              title: information
              href: www.smhi.se
              hreflang: en-US
        extents:
            spatial:
                bbox: [41.120975, 45.196243, 42.11576, 46.736885]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2024-04-01T00:00:00.000000000
                end: 2024-10-31T00:00:00.000000000
        providers:
        - type: edr
          name: xarray-edr
          data: s3://saferplaces.co/test/icisk/living_labs/test_ingestor/smhi/test_models_4.zarr
          x_field: geo_x
          y_field: geo_y
          time_field: time
          format:
            name: zarr
            mimetype: application/zip
          options:
            s3:
              anon: true
              requester_pays: false

    ingestor-smhi-process:
        type: process
        processor:
            name: pygeoapi_ingestor_plugin.IngestorSMHIProcessProcessor

    ingestor-cds-process:
        type: process
        processor:
            name: pygeoapi_ingestor_plugin.IngestorCDSProcessProcessor

    ingestor-smhi-vector-process:
        type: process
        processor:
            name: pygeoapi_ingestor_plugin.IngestorSMHIVectorProcessProcessor

    # ingestor-planetary-process:
    #     type: process
    #     processor:
    #         name: pygeoapi_ingestor_plugin.IngestorPlanetaryProcessProcessor
