# =================================================================
#
# Authors: Just van den Broecke <justb4@gmail.com>
#          Tom Kralidis <tomkralidis@gmail.com>
#          Francesco Bartoli <xbartolone@gmail.com>
#
# Copyright (c) 2019 Just van den Broecke
# Copyright (c) 2020 Tom Kralidis
# Copyright (c) 2020 Francesco Bartoli
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================


# Default config for base Docker Image, override via DockerVolume
# mapping with your own config.
server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:5000/ # https://i-cisk.dev.52north.org/data/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    ogc_schemas_location: /schemas.opengis.net
    manager:  # optional OGC API - Processes asynchronous job management
        name: TinyDB  # plugin name (see pygeoapi.plugin for supported process_manager's)
        connection: /tmp/pygeoapi-process-manager.db  # connection info to store jobs (e.g. filepath)
        output_dir: /tmp/  # temporary file area for storing job results (files)
logging:
    level: DEBUG
    logfile: /dev/stdout
metadata:
    identification:
        title: pygeoapi icisk
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
            - living-labs
            - i-cisk
            - 52north
            - gecko
        keywords_type: theme
        terms_of_service: 'FIXME: https://icisk.eu/about-icisk/'
        # might be useful to match server.url above!
        url: https://i-cisk.dev.52north.org/data/
    license:
        name: 'FIXME: TBD, maybe CC-BY 4.0 license'
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: 52°North I-Cisk Team
        url: https://52north.org/solutions/i-cisk/
    contact:
        name: Jürrens, Eike Hinderk
        position: Operator
        address: Martin-Luther-King-Weg 24
        city: Münster
        stateorprovince: NRW
        postalcode: 48155
        country: Germany
        phone: +49-251-396371-0
        email: e.h.juerrens+i-cisk-cloud-ops@52north.org
        url: https://52north.org/about-us/contact-us/
        hours: Mo-Fr 09:00-16:00 CE(S)T
        instructions: During hours of service. Off on weekends.
        role: pointOfContact
resources:
  #
  # ingestor processes
  #
  ingestor-cds-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSProcessProcessor
    type: process

  ingestor-creafforecast-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCREAFFORECASTProcessProcessor
    type: process

  ingestor-creafhistoric-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCREAFHISTORICProcessProcessor
    type: process

  ingestor-smhi-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorSMHIProcessProcessor
    type: process

  ingestor-smhi-vector-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorSMHIVectorProcessProcessor
    type: process

  # ingestor-planetary-process:
  #   processor:
  #     name: pygeoapi_ingestor_plugin.IngestorPlanetaryProcessProcessor
  #   type: process

  ingestor-cds-spi-historic-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSSPIHistoricProcessProcessor
    type: process

  ingestor-cds-spi-forecast-process:
    processor:
      name: pygeoapi_ingestor_plugin.IngestorCDSSPIForecastProcessProcessor
    type: process
