services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
    ports:
      - "5000:80"
    environment:
      - DEFAULT_BUCKET=
      - DEFAULT_REMOTE_DIR=
      - FSSPEC_S3_ENDPOINT_URL=
      - FSSPEC_S3_KEY=
      - FSSPEC_S3_SECRET=
      - INT_API_TOKEN=token
      - PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
      - PYGEOAPI_SERV_CONFIG=/pygeoapi/local.config.yml
  trigger_test:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - "/bin/bash"
    command: |
      -c 'python3 /pygeoapi/src/invoke/invoke_ingestor.py /invoke-input.json'
    environment:
      - API_ROOT=http://pygeoapi/
      - INT_API_TOKEN=token
    volumes:
    - ./creaf-ingest-input.json:/invoke-input.json
