services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
    ports:
      - "5000:80"
    environment:
      - DEFAULT_BUCKET=
      - DEFAULT_REMOTE_DIR=
      - FSSPEC_S3_ENDPOINT_URL=
      - FSSPEC_S3_KEY=
      - FSSPEC_S3_SECRET=
      - INT_API_TOKEN=token
      - PYGEOAPI_CONFIG=
  ingestion_test:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - "/bin/bash"
    command: |
      -c 'python3 /pygeoapi/src/invoke/invoke_ingestor.py " \
      {\"process\":\"ingestor-creafforecast-process\",\"payload\":{\"inputs\":{\"data_path\":\"/data/creafforecast/\",\"zarr_out\":\"s3://52n-i-cisk/data-ingestor/creaf_forecast.zarr\"}}} "'
    environment:
      - API_ROOT=http://pygeoapi/
      - INT_API_TOKEN=token
