services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/pygeoapi/local.config.yml
      - ./scheduler.yaml:/scheduler.yaml
    ports:
      - "5000:80"
    environment:
      - DEFAULT_BUCKET=52n-i-cisk
      - DEFAULT_REMOTE_DIR=data-ingestor/
      - FSSPEC_S3_ENDPOINT_URL=https://obs.eu-de.otc.t-systems.com
      - FSSPEC_S3_KEY=
      - FSSPEC_S3_SECRET=
