from .ingestor_smhi_process import IngestorSMHIProcessProcessor
from .ingestor_cds_process import IngestorCDSProcessProcessor
# from .ingestor_planetary_process import IngestorPlanetaryProcessProcessor
