name: "lint and format after push"
concurrency:
  group: "push-lint-and-format"
  cancel-in-progress: true
on:
  # all pushes and PRs, but not tags
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
jobs:
  lint-format-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@v5
    -
      name: install ruff
      run: |
        pip3 install ruff
    -
      name: run linter and formatter
      run: |
        ruff check
        ruff check --select I
        ruff format --diff
